fos_rest:
    param_fetcher_listener: force
    view:
        view_response_listener: true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    serializer:
        groups: ['default']
    exception:
        enabled: true
        codes:
           { 
                App\Exception\ResourceValidationException: 400,
                Symfony\Component\HttpKernel\Exception\BadRequestHttpException: 400,
                Symfony\Component\Security\Core\Exception\AuthenticationException: 401,
                Doctrine\ORM\OptimisticLockException: HTTP_CONFLICT,
                Symfony\Component\Security\Core\Exception\AccessDeniedException: 403,
                Symfony\Component\Routing\Exception\ResourceNotFoundException: 404,
           }
    format_listener:
        enabled: true
        rules:
             - { path: '^/admin', stop: true }
             - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: false }
             - { path: '^/', priorities: ['html'], fallback_format: html, prefer_extension: false }


        